id: discrete
title: 离散化
file: index.md
code_template:
  -
    title: discrete 离散化简单
    tags: ['discrete']
    desc: 离散化简单模板
    code: /code/base/discrete离散化_手写.cpp
  -
    title: discrete 离散化
    tags: ['discrete']
    desc: 离散化模板
    code: /code/base/discrete离散化_unique.cpp
