id: graph_traversal
title: 图的遍历
file: "index.md"
code_template:
  -
    title: "dfs遍历图"
    tags:
      - graph
    code: ./graph_dfs_template.cpp
  -
    title: "无向图连通分支"
    tags:
      - graph
      - connected
    code: ./graph_dfs_find_all_connected_commponent.cpp
