id: sgt_preface
title: "前言"
file: "index.md"
code_template:
  -
    title: sgt单点更新
    tags: ['sgt']
    desc: sgt单点更新
    code: /code/data-struture/segment_tree/point_add_range_sum.cpp
  -
    title: sgt区间更新
    tags: ['sgt']
    desc: sgt区间更新
    code: /code/data-struture/segment_tree/range_assign_range_sum.cpp
